### ISSUE TITLE
[PAGE ISSUE]: '配置 flavors 构建双端'

### ISSUE THREAD

**Issue by lzou** [cfug/flutter.cn#1289] opened 2023-05-16 01:44 UTC
### 页面 URL

https://flutter.cn/docs/deployment/flavors/

### 页面源地址

https://github.com/cfug/flutter.cn/tree/master/src/deployment/flavors.md

### 描述问题

jumbled pages

### 期望如何修复

normal display

### 附加信息

![image](https://github.com/cfug/flutter.cn/assets/2950642/c74bfcb0-15c4-4f01-a17b-114ccf6473d8)

**Comment by AlexV525** [comment] 2023-05-16 02:03
Duplicate of #1248

**Closed by AlexV525** 2023-05-16 02:03 UTC
Labels: E: 页面问题
